### ISSUE TITLE
Building any project with plugin present causes immediate crash

### ISSUE THREAD

**Issue by liam-coll** [miquido/AR_quido#16]
Upon attempting to debug the plugin on my Samsung A52, the build reaches the following line:
`√  Built build\app\outputs\flutter-apk\app-debug.apk.`
The app launches on the phone and immediately exits, leaving no error message or anything.
Tested on both my own project and the example

**Comment by PiotrMitkowski** [comment]
Hello @liam-coll!

Do you mind checking the native Android logs in the `Logcat` tab of the Android Studio? There is usually more information there, especially if the app crashes before the Flutter engine is fully started.

Could you also confirm, that you've inserted the Easy AR Sense License Key in the correct place of the `AndroidManifest.xml` (as mentioned [here](https://github.com/miquido/AR_quido?tab=readme-ov-file#android))?

Thanks!

**Comment by liam-coll** [comment]
Nice! Logcat provided the clarity - hadn't changed the package name on the metadata.
Thanks for the quick and helpful reply, and for helping out a newbie to the app dev world!

**Comment by PiotrMitkowski** [comment]
You're welcome, good luck with your AR project! 💪
